{
  "runOn": [
    {
      "minServerVersion": "4.0",
      "topology": [
        "replicaset"
      ]
    },
    {
      "minServerVersion": "4.1.7",
      "topology": [
        "sharded",
        "load-balanced"
      ]
    }
  ],
  "data": [
    {
      "_id": 1,
      "x": 11
    },
    {
      "_id": 2,
      "x": 22
    }
  ],
  "tests": [
    {
      "description": "BulkWrite fails with a RetryableWriteError label after two connection failures",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 2
        },
        "data": {
          "failCommands": [
            "update"
          ],
          "closeConnection": true
        }
      },
      "operation": {
        "name": "bulkWrite",
        "arguments": {
          "requests": [
            {
              "name": "deleteOne",
              "arguments": {
                "filter": {
                  "_id": 1
                }
              }
            },
            {
              "name": "insertOne",
              "arguments": {
                "document": {
                  "_id": 3,
                  "x": 33
                }
              }
            },
            {
              "name": "updateOne",
              "arguments": {
                "filter": {
                  "_id": 2
                },
                "update": {
                  "$inc": {
                    "x": 1
                  }
                }
              }
            }
          ],
          "options": {
            "ordered": true
          }
        }
      },
      "outcome": {
        "error": true,
        "result": {
          "errorLabelsContain": [
            "RetryableWriteError"
          ]
        },
        "collection": {
          "data": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      }
    }
  ]
}
